### ISSUE TITLE
Can't access Gantry5 in Grav Admin Panel

### ISSUE THREAD

**Issue by djahnie** [yunity/foodsaving.world#2]
I wanted to play around with that new page a bit, created a user for me, accessed the admin panel and looked for things to change, so that the landing page would display something other than the Gantry5 default text. But when I tried accessing the Gantry5 section I got the following error:
![image](https://user-images.githubusercontent.com/17573771/30324619-fcfaf2c8-97c1-11e7-8876-442be42e6d05.png)
What to do?

**Comment by nicksellen** [comment]
should be all fixed now. related to https://github.com/getgrav/grav/issues/880 perhaps. had to git rm --cached some of the plugin and theme dirs then readd.

**Comment by djahnie** [comment]
Perfect, thanks!
